import type { Metadata } from "next";
import { Crimson_Text } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});

const crimsonText = Crimson_Text({
	weight: ["400", "600", "700"],
	subsets: ["latin"],
	display: "swap",
	variable: "--font-crimson-text",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={` ${crimsonText.variable} ${geistSans.className} antialiased`}
			>
				<main className="relative min-h-screen w-full">
					<div className="mx-auto max-w-[568px]">{children}</div>
				</main>
			</body>
		</html>
	);
}
